name: "build Check"

on:
  push:
    branches:
      - "*"

jobs:
  tagged-release:
    name: "Build Check"
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install Protoc
      uses: arduino/setup-protoc@v1

    - name: Build Unix
      run: make test